### ISSUE TITLE
Tracking issue for exhaustively documenting the client

### ISSUE THREAD

**Issue by iTranscend** [near/near-jsonrpc-client-rs#51]
This is a tracking issue for the bounty to exhaustively document the jsonrpc client https://github.com/near/bounties/issues/77

A series of PRs documenting each of the artefacts below will be provided to complete this. 
- [ ] Document the `tx` jsonrpc method
- [ ] Document the `block` jsonrpc method
- [ ] Document the `broadcast_tx_async` jsonrpc method
- [ ] Document the `broadcast_tx_commit` jsonrpc method
- [ ] Document the `chunk` jsonrpc method
- [ ] Document the `gas_price` jsonrpc method
- [ ] Document the `health` jsonrpc method
- [ ] Document the `light_client_proof` jsonrpc method
- [ ] Document the `network_info` jsonrpc method
- [ ] Document the `next_light_client` jsonrpc method
- [ ] Document the `query` jsonrpc method
- [ ] Document the `status` jsonrpc method
- [ ] Document the `validators` jsonrpc method

Experimental methods:
- [ ] Document the `changes_in_block` method
- [ ] Document the `changes` method
- [ ] Document the `check_tx` method
- [ ] Document the `genesis_config` method
- [ ] Document the `receipt` method
- [ ] Document the `tx_status` method
- [ ] Document the `validators_ordered` method

Sandbox methods:
- [ ] Document the `fast_forward` method
- [ ] Document the `patch_state` method

**Comment by miraclx** [comment]
This effort is now complete.

@frol, thanks for taking the time to parse through it all.

And thanks, @iTranscend, for preparing these PRs. Sorry, it took a while 😅
